#!/bin/bash -e


# Prepare data directory due to volume
if [ ! -d ${METABASE_HOME}/data ]; then
  mkdir -p ${METABASE_HOME}/data \
  && chown user:root ${METABASE_HOME}/data \
  && chmod 775 ${METABASE_HOME}/data
fi


# Prepare data/dbs directory due to volume
if [ ! -d ${METABASE_HOME}/data/dbs ]; then
  mkdir -p ${METABASE_HOME}/data/dbs \
  && chown user:root ${METABASE_HOME}/data/dbs \
  && chmod 775 ${METABASE_HOME}/data/dbs
fi


# Prepare data/plugins directory due to volume
if [ ! -d ${METABASE_HOME}/data/plugins ]; then
  mkdir -p ${METABASE_HOME}/data/plugins \
  && chown user:root ${METABASE_HOME}/data/plugins \
  && chmod 775 ${METABASE_HOME}/data/plugins
fi


# Configuring Metabase Environment Variables
export MB_JETTY_PORT=3000
export MB_DB_FILE=${METABASE_HOME}/data/dbs/metabase.db


# Execute Everything from Entries
exec "$@"
