FROM surnet/alpine-wkhtmltopdf:3.16.0-0.12.6-full AS builder

FROM alpine:3.16

LABEL org.opencontainers.image.authors="EWZ Engineering <engineering@mytens.co.id>" \
      io.k8s.description="Alpine (3.16) WKHTMLTOPDF golang 1.19" \
      io.k8s.display-name="Alpine (3.16) WKHTMLTOPDF golang 1.19" \
      io.openshift.non-scalable="false" \
      io.openshift.tags="builder,alpine,glibc,wkhtmltopdf,golang" \
      summary="Virtual Machine (VM) like container platform WKHTMLTOPDF with Golang 1.19" \
      vendor="Alpine" \
      release="1"

ENV LANG="C.UTF-8" \
    LC_ALL="C.UTF-8" \
    TZ="Asia/Jakarta"

WORKDIR /usr/src/app

# Install glibc
ENV GLIBC_VERSION="2.35-r0"
COPY install_glibc_alpine.sh .
RUN /bin/sh install_glibc_alpine.sh

# Install wkhtmltopdf
ENV WKHTMLTOPDF_VERSION="0.12.6"
COPY install_wkhtmltopdf_alpine.sh .
RUN /bin/sh install_wkhtmltopdf_alpine.sh
COPY --from=builder /bin/wkhtmltopdf /bin/wkhtmltopdf
COPY --from=builder /bin/wkhtmltoimage /bin/wkhtmltoimage
COPY --from=builder /lib/libwkhtmltox* /bin/

# Install golang
ENV GOLANG_VERSION="1.19" \
    GOPATH="/go" \
    PATH=/go/bin:/usr/local/go/bin:${PATH}
COPY install_golang_alpine.sh .
RUN /bin/sh install_golang_alpine.sh

# Custom configuration for Alpine Linux
COPY configure_alpine.sh .
RUN /bin/sh configure_alpine.sh

