FROM debian:11

LABEL org.opencontainers.image.authors="Lutfa Ibtihaji Ilham <lutfailham96@gmail.com>"
LABEL io.k8s.description="Debian (11) Kafka-UI"
LABEL io.k8s.display-name="Debian (11) Kafka-UI"
LABEL io.openshift.non-scalable="false"
LABEL io.openshift.tags="runner,debian,kafka"
LABEL summary="Virtual Machine (VM) like container platform with Kafka-UI"
LABEL vendor="Debian"
LABEL release="1"

# Fix Log4j vulnerabilty issue
ENV LOG4J_FORMAT_MSG_NO_LOOKUPS=true \
    JAVA_OPTS="-Dlog4j2.formatMsgNoLookups=true"

ENV PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

ENV LANG="C.UTF-8" \
    LC_ALL="C.UTF-8" \
    TZ="Asia/Jakarta"

ENV KAFKA_UI_VERSION=0.4.0

WORKDIR /usr/src/app

RUN apt-get update -y \
    && apt-get install -y --no-install-recommends curl openjdk-11-jre \
    && curl -Lo kafka-ui-api.jar "https://github.com/provectus/kafka-ui/releases/download/v${KAFKA_UI_VERSION}/kafka-ui-api-${KAFKA_UI_VERSION}.jar" \
    && apt-get remove -y --purge curl \
    && apt-get autoremove -y --purge \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

USER nobody:nobody

EXPOSE 8080

ENTRYPOINT ["/bin/sh"]

CMD ["java", "${JAVA_OPTS}", "-jar" ,"kafka-ui-api.jar"]

