FROM debian:11-slim

LABEL org.opencontainers.image.authors="EWZ Engineering <engineering@mytens.co.id>" \
      io.k8s.description="Debian (11) Kafka-UI" \
      io.k8s.display-name="Debian (11) Kafka-UI" \
      io.openshift.non-scalable="false" \
      io.openshift.tags="runner,debian,kafka" \
      summary="Virtual Machine (VM) like container platform with Kafka-UI" \
      vendor="Debian" \
      release="1"

ENV LANG="C.UTF-8" \
    LC_ALL="C.UTF-8" \
    TZ="Asia/Jakarta" \
    DEBIAN_FRONTEND="noninteractive"

WORKDIR /usr/src/app

# Install kafka-ui
ENV KAFKA_UI_VERSION="0.4.0" \
    LOG4J_FORMAT_MSG_NO_LOOKUPS="true" \
    JAVA_OPTS="-Dlog4j2.formatMsgNoLookups=true"
COPY install_kafkaui_debian.sh .
RUN /bin/sh install_kafkaui_debian.sh

# Custom configuration for Debian
COPY configure_debian.sh .
RUN /bin/sh configure_debian.sh

USER nobody:nobody

EXPOSE 8080

CMD ["/bin/sh", "-c", "java ${JAVA_OPTS} -jar kafka-ui-api.jar"]

