FROM alpine:3.16

LABEL org.opencontainers.image.authors="EWZ Engineering <engineering@mytens.co.id>" \
      io.k8s.description="Alpine (3.16) Trivy 0.34" \
      io.k8s.display-name="Alpine (3.16) Trivy 0.34" \
      io.openshift.non-scalable="false" \
      io.openshift.tags="runner,security,alpine" \
      summary="Virtual Machine (VM) like container platform with Trivy" \
      vendor="Alpine" \
      release="1"

ENV LANG="C.UTF-8" \
    LC_ALL="C.UTF-8" \
    TZ="Asia/Jakarta"

WORKDIR /usr/src/app

# Install trivy
ENV TRIVY_VERSION="0.34.0"
COPY install_trivy_alpine.sh .
RUN /bin/sh install_trivy_alpine.sh

# Custom configuration for Alpine Linux
COPY configure_alpine.sh .
RUN /bin/sh configure_alpine.sh


ENTRYPOINT ["trivy"]

