FROM alpine:3.16

LABEL org.opencontainers.image.authors="EWZ Engineering <engineering@mytens.co.id>"
LABEL io.k8s.description="Alpine (3.16) Trivy 0.31"
LABEL io.k8s.display-name="Alpine (3.16) Trivy 0.31"
LABEL io.openshift.non-scalable="false"
LABEL io.openshift.tags="runner,security,alpine"
LABEL summary="Virtual Machine (VM) like container platform with Trivy"
LABEL vendor="Alpine"
LABEL release="1"

ENV LANG="C.UTF-8" \
    LC_ALL="C.UTF-8" \
    TZ="Asia/Jakarta"

ENV TRIVY_VERSION="0.31.2"

WORKDIR /usr/src/app

# Install Trivy
RUN apk add --no-cache \
        curl \
        ca-certificates \
        tar; \
    sha256="57321e970a485211eaaeee1e0bb44bf5b5ba939686a2c3052050c4c3e8154d4c"; \
    curl -Lo trivy.tar.gz https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-ARM64.tar.gz; \
    echo "${sha256}  trivy.tar.gz" | sha256sum -c -; \
    tar -xzvpf trivy.tar.gz; \
    cp -avp trivy /usr/local/bin/trivy; \
    mkdir -p /contrib; \
    cp -avp contrib/*.tpl /contrib; \
    rm -rf *

# Add tzdata
RUN apk add --no-cache tzdata

# Cleanup
RUN apk del --no-cache --no-network \
        tar; \
    rm -rf /var/cache/apk/*

