FROM debian:11-slim

LABEL org.opencontainers.image.authors="EWZ Engineering <engineering@mytens.co.id>"
LABEL io.k8s.description="Debian (11) OCI"
LABEL io.k8s.display-name="Debian (11) OCI"
LABEL io.openshift.non-scalable="false"
LABEL io.openshift.tags="runner,debian,oracle"
LABEL summary="Virtual Machine (VM) like container platform with Oracle Instant Client"
LABEL vendor="Debian"
LABEL release="1"

ENV LANG="C.UTF-8" \
    LC_ALL="C.UTF-8" \
    TZ="Asia/Jakarta" \
    DEBIAN_FRONTEND="noninteractive"

ENV INSTANT_CLIENT_VERSION="21.7.0" \
    PATH="/opt/oracle/instantclient:${PATH}" \
    LD_LIBRARY_PATH="/opt/oracle/instantclient:${LD_LIBRARY_PATH}" \
    ORACLE_BASE="/opt/oracle/instantclient" \
    TNS_ADMIN="/opt/oracle/instantclient" \
    ORACLE_HOME="/opt/oracle/instantclient"

WORKDIR /usr/src/app

# Prerequisites
RUN apt-get update -y; \
    apt-get install -y --no-install-recommends \
        libaio1 \
        ca-certificates \
        unzip \
        wget

# Install instantclient
RUN wget -O instantclient.zip "https://download.oracle.com/otn_software/linux/instantclient/217000/instantclient-basiclite-linux.x64-${INSTANT_CLIENT_VERSION}.0.0dbru.zip" \
        && unzip instantclient.zip \
        && rm -rf instantclient.zip \
        && mkdir -p /opt/oracle/instantclient \
        && mv instantclient_*/* /opt/oracle/instantclient/ \
        && rm -rf instantclient_* \
        && echo "/opt/oracle/instantclient" > /etc/ld.so.conf.d/oracle-instantclient.conf \
        && ldconfig

# Cleanup
RUN apt-get remove -y --purge wget unzip \
     && apt-get autoremove -y --purge \
     && apt-get autoclean -y \
     && apt-get clean -y \
     && rm -rf rm -rf /var/lib/apt/lists/*

USER nobody:nobody

