FROM debian:11

LABEL org.opencontainers.image.authors="EWZ Engineering <engineering@mytens.co.id>"
LABEL io.k8s.description="Debian (11)"
LABEL io.k8s.display-name="Debian (11)"
LABEL io.openshift.non-scalable="false"
LABEL io.openshift.tags="runner,debian"
LABEL summary="Virtual Machine (VM) like container platform"
LABEL vendor="Debian"
LABEL release="1"

ENV LANG="C.UTF-8" \
    LC_ALL="C.UTF-8" \
    TZ="Asia/Jakarta" \
    DEBIAN_FRONTEND="noninteractive"

WORKDIR /usr/src/app

USER nobody:nobody

