FROM debian:11-slim

LABEL org.opencontainers.image.authors="EWZ Engineering <engineering@mytens.co.id>" \
      io.k8s.description="Debian (11)" \
      io.k8s.display-name="Debian (11)" \
      io.openshift.non-scalable="false" \
      io.openshift.tags="runner,debian" \
      summary="Virtual Machine (VM) like container platform" \
      vendor="Debian" \
      release="1"

ENV LANG="C.UTF-8" \
    LC_ALL="C.UTF-8" \
    TZ="Asia/Jakarta" \
    DEBIAN_FRONTEND="noninteractive"

WORKDIR /usr/src/app

# Custom configuration for Debian
COPY configure_debian.sh .
RUN /bin/sh configure_debian.sh

USER nobody:nobody

