FROM debian:11-slim

LABEL org.opencontainers.image.authors="EWZ Engineering <engineering@mytens.co.id>"
LABEL io.k8s.description="Debian (11) Node.js 10"
LABEL io.k8s.display-name="Debian (11) Node.js 10"
LABEL io.openshift.non-scalable="false"
LABEL io.openshift.tags="runner,builder,debian,nodejs"
LABEL summary="Virtual Machine (VM) like container platform with Node.js 10"
LABEL vendor="Debian"
LABEL release="1"

ENV LANG="C.UTF-8" \
    LC_ALL="C.UTF-8" \
    TZ="Asia/Jakarta" \
    DEBIAN_FRONTEND="noninteractive"

WORKDIR /usr/src/app

# Install Node.js
ENV NODE_VERSION="10.24.1"
COPY install_nodejs_debian.sh .
RUN /bin/sh install_nodejs_debian.sh

# Install yarn
ENV YARN_VERSION="1.22.5"
COPY install_yarn_debian.sh .
RUN /bin/sh install_yarn_debian.sh

# Custom configuration for Debian
COPY configure_debian.sh .
RUN /bin/sh configure_debian.sh

COPY docker-entrypoint.sh /usr/local/bin

ENTRYPOINT ["docker-entrypoint.sh"]

